config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  get 'payment', to: 'payment#index'
  post 'payment', to: 'payment#charge'

  resources :products

  root to: 'visitors#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'stripe'
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable, :omniauthable

	has_many :products

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = SecureRandom.urlsafe_base64
		    access_code = auth.credentials.token
	      	publishable_key = auth.info.stripe_publishable_key
		end
	end

	def charge_account(token, amount)
		Stripe.api_key = ENV['stripe_secret_key']
	  	# Get the credit card details submitted by the form

		amount = (amount.to_f * 100).to_i

		# Calculate the fee amount that goes to the application.
	    fee = (amount * 0.10).to_i

	    result = {}
	    begin
			# Create the charge on Stripe's servers - this will charge the user's card
			charge = Stripe::Charge.create({
			    :amount => amount, # amount in cents
			    :currency => "usd",
			    :source => token,
			    :description => "Example charge",
			    :application_fee => fee, # amount in cents
			}, {:stripe_account => self.uid}
			)

			result[:response] = 200
			result[:charge] = charge

		rescue Stripe::CardError => e
	      error = e.json_body[:error][:message]
	      result[:response] = 500
	      result[:error] = "Charge failed! #{error}"
	    end
	   	
	   	result

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def stripe_connect
	    @user = User.from_omniauth(request.env["omniauth.auth"])
	    
	    if @user.persisted?
	      # anything else you need to do in response..
	      sign_in_and_redirect @user, :event => :authentication
	      set_flash_message(:notice, :success, :kind => "Stripe") if is_navigational_format?
	    else
	      session["devise.stripe_connect_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def index
    if params[:product].nil? || params[:product].blank?
      redirect_to root_path
    else 
      @product = Product.find(params[:product])
      @amount = params[:amount]
      @user = @product.user
    end
  end

  def charge
    product = Product.find(params[:product_id])
  	user = product.user

  	result = user.charge_account(
  		params[:stripeToken],
  		params[:amount]
  	)

  	if result[:response] == 200
      charge = result[:charge]
      email = params[:email]
      SendEmailJob.set(wait: 10.seconds).perform_later(email, charge.id, product)
  		render 'payment/thank_you'
  	else
  		flash[:alert] = result[:error]
  		redirect_to(:back)
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :amount_1, :amount_2, :amount_3, :amount_4, :description)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		@products = Product.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %span
        = link_to "Revv", root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if current_user 
	%li.links
		= link_to "Products", edit_user_registration_path
- else
	%li.links
		= link_to "Connect", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Revv Tech'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Revv Tech'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      / = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/payment/index.html.haml
%script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
:javascript
	Stripe.setPublishableKey('#{ENV['stripe_publishable_key']}');

= javascript_include_tag 'payment'
%section.container
	.row
		.col-md-10.col-md-offset-1
			%header
				%h2 Your Order
				%hr

			.col-md-3
				%p=@product.name 
			.col-md-6
				%p=@product.description
			.col-md-3
				.pull-right
					%p Amount: #{@amount}
			.col-md-12
				.total.pull-right
					%b Total: $#{@amount}
			%hr
	.row
		.form-horizontal
			= form_tag payment_path, :method => :post, id: "payment-form" do
				= hidden_field_tag :amount, @amount
				= hidden_field_tag :product_id, @product.id
				.col-md-10.col-md-offset-1
					%h2 Payment Information
					%hr
				.col-md-11.col-md-offset-1
					%fieldset.credit_card
						.form-group
							%label.control-label.col-md-2(for="email") Email
							.col-md-6
								%input.form-control#credit-card-number(type="email" name="email")
								%small We will only email you an order confirmation. We promise.
					%fieldset.credit_card

						.form-group
							%label.control-label.col-md-2(for="credit-card-number") Credit Card Number
							.col-md-6
								%input.form-control#credit-card-number(type="text" data-stripe="number" maxlength="16")
								.payment-errors
						.form-group
							%label.control-label.col-md-2(for="security-code") Security Code
							.col-md-6
								%input.form-control#security-code(type="text" data-stripe="cvc")
						.form-group
							%label.control-label.col-md-2 Expiration
							.col-md-3
								= select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: "exp-month"})
							.col-md-2
								= select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: "exp-year"})

					%fieldset.actions.control-group.col-md-offset-2
						.controls
							%input(type="submit" value="Charge" class="btn btn-default")

app/views/payment/thank_you.html.haml
%section.container
	.row
		.col-md-10.col-md-offset-1
			%header
				%h2 Thank you for your purchase
				%hr

			%p You will receive an email, shortly.

app/views/products/_form.html.haml
.container
  .row
    = form_for @product, html: { class: "form form-horizontal product" } do |f|
      .form-group
        = f.label :name, class: 'control-label col-lg-2'
        .col-lg-10
          = f.text_field :name, class: 'form-control', required: true
        = f.error_span(:name)
      .form-group
        = f.label "Donate Amount", class: 'control-label col-lg-3'
        .col-lg-2
          = f.text_field :amount_1, class: 'form-control', required: true, placeholder: 10
        .col-lg-2  
          = f.text_field :amount_2, class: 'form-control', required: true, placeholder: 50
        .col-lg-2
          = f.text_field :amount_3, class: 'form-control', required: true, placeholder: 75
        .col-lg-2
          = f.text_field :amount_4, class: 'form-control', required: true, placeholder: 100
        = f.error_span(:price)
      .form-group
        = f.label :description, class: 'control-label col-lg-2'
        .col-lg-10
          = f.text_area :description, class: 'form-control', required: true
        = f.error_span(:description)
      .form-group
        .col-lg-offset-2.col-lg-10
          = f.submit nil,class: 'btn btn-primary'
          = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn btn-default'

app/views/products/_product.html.haml
.col-md-4
  .product-img
    =image_tag("revv-logo.jpg")
  .description
    %h4= product.name
    %p= product.description
  .amount
    %label Select amount:
    %br
    .btn-group.amount-selector
      %button{"data-path" => payment_path(product: product, amount: number_with_precision(product.amount_1, precision: 0)), class: "btn btn-default active"}= number_with_precision(product.amount_1, precision: 0)
      %button{"data-path" => payment_path(product: product, amount: number_with_precision(product.amount_2, precision: 0)), class: "btn btn-default"}= number_with_precision(product.amount_2, precision: 0)
      %button{"data-path" => payment_path(product: product, amount: number_with_precision(product.amount_3, precision: 0)), class: "btn btn-default"}= number_with_precision(product.amount_3, precision: 0)
      %button{"data-path" => payment_path(product: product, amount: number_with_precision(product.amount_4, precision: 0)), class: "btn btn-default"}= number_with_precision(product.amount_4, precision: 0)
  .text-center
    - if view_only == :false
      .pay-button
        = link_to "Donate", payment_path(product: product, amount: number_with_precision(product.amount_1, precision: 0)), :class => 'btn btn-primary btn-large btn-block'
    - else
      = link_to "View on Homepage", root_path(anchor: "products"), :class => 'btn btn-primary btn-large btn-block'

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/index.html.haml
- model_class = Product
.container
  .row
    .col-md-12
      .page-header
        %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
      %table.table.table-striped
        %thead
          %tr
            %th= model_class.human_attribute_name(:id)
            %th= model_class.human_attribute_name(:name)
            %th= model_class.human_attribute_name(:amount)
            %th= model_class.human_attribute_name(:description)
            %th= model_class.human_attribute_name(:created_at)
            %th=t '.actions', :default => t("helpers.actions")
        %tbody
          - @products.each do |product|
            %tr
              %td= link_to product.id, product_path(product)
              %td= product.name
              %td Four
              %td= product.description
              %td=l product.created_at
              %td
                = link_to "View", product_path(product), :class => 'btn btn-default btn-xs'
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-default btn-xs'
                = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

      = link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/show.html.haml
- model_class = Product
%section.product-section
  .container
    .row
      .col-md-10.col-md-offset-1
        .page-header
          .pull-right 
            = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn btn-default'
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn btn-default'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
          %h1=t '.title', :default => model_class.model_name.human.titleize
      
      .col-md-10.col-md-offset-4
        .products
          = render :partial => 'product', :locals => { :product => @product, :view_only => :true }

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/visitors/index.html.haml
%section.landing-section
	.cover
		.wrapper
			.container
				.row
					.col-md-5
						%h2.title Revv Technical Challenge
					.col-md-5.content
						%h2 ONE-CLICK PAYMENTS TO POWER YOUR CAUSE.
						= link_to "The Challenge", "#challenge", :class => 'btn btn-default btn-clear btn-large scroll-button'

%section.about-section{id: 'challenge'}
	.container
		.row
			.col-md-12
				%h2 The Challenge
				%hr
				.col-md-10.col-md-offset-1
					.text-center
						.col-md-8.col-md-offset-2
							- if current_user
								%p Add, View or Modify products
								= link_to "Products", products_path, :class => 'btn btn-primary btn-large'
							- else
								%p Sign in to use Stripe Connect or add products 
								= link_to "Sign in", new_user_session_path, :class => 'btn btn-primary btn-large'

%section.product-section{id: 'products'}
	.container
		.row
			.col-md-12
				%h2 Donation Campaigns
				%hr
				.products
					- if current_user
						- @products.each do |product|
							= render :partial => 'products/product', :locals => { :product => product, :view_only => :false }
				- if @products.count == 0 
					%p No products available